run:
  skip-files:
    - "./mock/.*.go"
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gosec
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - interfacer
    - unconvert
    - goconst
    - unparam
    - nakedret
    - scopelint
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/tsovak/rest-api-demo
