dist: bionic

services:
  - docker

language: go
go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - make install_deps

script:
  - make test test-with-coverage
  - make build
