version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:12.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#    network_mode: "host"