// Code generated by MockGen. DO NOT EDIT.
// Source: pg_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	v9 "github.com/go-pg/pg/v9"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPostgresClient is a mock of PostgresClient interface
type MockPostgresClient struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresClientMockRecorder
}

// MockPostgresClientMockRecorder is the mock recorder for MockPostgresClient
type MockPostgresClientMockRecorder struct {
	mock *MockPostgresClient
}

// NewMockPostgresClient creates a new mock instance
func NewMockPostgresClient(ctrl *gomock.Controller) *MockPostgresClient {
	mock := &MockPostgresClient{ctrl: ctrl}
	mock.recorder = &MockPostgresClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPostgresClient) EXPECT() *MockPostgresClientMockRecorder {
	return m.recorder
}

// GetConnection mocks base method
func (m *MockPostgresClient) GetConnection() *v9.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection")
	ret0, _ := ret[0].(*v9.DB)
	return ret0
}

// GetConnection indicates an expected call of GetConnection
func (mr *MockPostgresClientMockRecorder) GetConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockPostgresClient)(nil).GetConnection))
}

// Close mocks base method
func (m *MockPostgresClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockPostgresClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPostgresClient)(nil).Close))
}
